### ISSUE TITLE
The CLI should display if an update has been waived

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2267]
Similar to #2266, the CLI should display waiver information on updates.

**Comment by bowlofeggs** [comment]
To clarify, this change should be done on the ```edit``` and ```query``` subcommands.

**Comment by bowlofeggs** [comment]
On Sun, 2018-12-02 at 19:04 +0100, @sebwoj wrote:
> Where can I find that infomration?
> New models.update field(bodhi can set this field to true after request to "API waive update GW test")?
> Or when update have some failed greenvaive tests and test_gating_status is waiting(waived_update information should be cleared after second GW test are passed and update_test_gating_status is called)?

This may take some research. I think the Greenwave response might have the waiver information in it, but if it doesn't we may need to query WaiverDB instead.

**Comment by sebwoj** [comment]
In greenwave repo I found something usefull:
https://pagure.io/greenwave/blob/master/f/greenwave/api_v1.py#_253
How waiver information should be printed?
1. Bool value:

```
CI Status: no tests are required
   Waived: True
  Request: testing
```

2. Same as for example: comments:
```
    Comments: bodhi - 2018-12-08 14:27:51 (karma 0)
              This update has been submitted for testing by ignatenkobrain.
              bodhi - 2018-12-09 04:46:51 (karma 0)
              This update has been pushed to testing.
              bodhi - 2018-12-10 16:25:51 (karma 0)
              ignatenkobrain edited this update.  New build(s):  - meson-
              latest-20181209203125.06d0a27d  Removed build(s):  - meson-
              latest-20181208132651.06d0a27d  Karma has been reset.
              bodhi - 2018-12-10 16:25:52 (karma 0)
              This update has been submitted for testing by ignatenkobrain.

```
Example:
```
CI Status: no tests are required
  Waivers:
                  username: ralph
                  comment': This is fine.
                  product_version: fedora-27
                  time: 2018-12-08 14:27:51
                  proxied_by: null,
                  subject_type: koji_build
                  subject_identifier: cross-gcc-7.0.1-0.3.fc26
                  testcase: dist.rpmlint
  Request: testing
```
I this case, what information do we need from GW response?
