### ISSUE TITLE
Can't submit modular update for F28 if it was built against F29

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#2510]
```yaml
document: modulemd
version: 2
data:
  summary: Stratis Storage
  description: Easy to use local storage management.
  license:
    module: [MIT]
  dependencies:
    - buildrequires:
        platform: [f29]
      requires:
        platform: []
  references:
    community: https://github.com/stratis-storage
    documentation: https://stratis-storage.github.io
    tracker: https://github.com/stratis-storage/stratisd/issues
  api:
    rpms:
      - stratisd
  profiles:
    default:
      rpms:
        - stratisd
        - stratis-cli
  components:
    rpms:
      stratisd:
        rationale: |
          Daemon that manages a pool of block devices to create flexible filesystems.

          Main component.
```

This is the yaml I have built module from. tl;dr it means it builds on f29 and works on f28, f29, f30, …

When I try to submit an update, bodhi fails with message:
```
Builds : Cannot find release associated with build: stratis-master-20180726133047.b33445dc, tags: ['f29-modular']
```
