### ISSUE TITLE
Implement nagmail script

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#298]
We need a job that comments on updates once they meet the minimum amount of time in testing, etc.

https://github.com/fedora-infra/bodhi/blob/master/bodhi/jobs.py#L74

**Comment by ralphbean** [comment]
We would run this with cron now, right?

**Comment by lmacken** [comment]
Yeah, similar to `bodhi/scripts/expire_overrides.py`

**Comment by robert-scheck** [comment]
+1 for nagmails

**Comment by ralphbean** [comment]
Freeze should lift on Tuesday, so we'll get another shot at this after that.

**Comment by lmacken** [comment]
Untested, but does this look good for our `bodhi2/backend/tasks/main.yml` ansible role?

```yaml
- name: bodhi-approve-testing cron job.                                         
  cron: name="bodhi-approve-testing" hour="*/6" user="masher"                   
        job="/usr/bin/bodhi-approve-testing /etc/bodhi/production.ini"                   
        cron_file=bodhi-approve-testing-job                                     
  when: inventory_hostname.startswith('bodhi-backend02') and env == "production"
  tags:                                                                         
  - config                                                                      
  - bodhi                                                                       
  - cron                                                                        

```
